# color pair definitions for shaders

BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE =\
0    , 1  , 2    , 3     , 4   , 5      , 6   , 7
pairs={
 11:(YELLOW, BLACK)
,12:(YELLOW, RED)
,13:(YELLOW, GREEN)
,14:(WHITE,  YELLOW)
,15:(YELLOW, BLUE)
,16:(YELLOW, MAGENTA)
,17:(YELLOW, CYAN)
,18:(WHITE,  WHITE)

,21:(BLACK, BLACK)
,22:(BLUE,  RED)
,23:(BLUE,  GREEN)
,24:(BLUE,  YELLOW)
,25:(BLACK, BLUE)
,26:(BLUE,  MAGENTA)
,27:(BLUE,  CYAN)
,28:(BLUE,  WHITE)

,31:(BLUE    ,BLACK)
,32:(RED     ,BLUE)
,33:(GREEN   ,BLUE)
,34:(YELLOW  ,BLUE)
,35:(BLUE    ,BLACK)
,36:(MAGENTA ,BLUE)
,37:(CYAN    ,BLUE)
,38:(WHITE   ,BLUE)

,41:(BLUE  ,BLACK)
,42:(BLUE  ,BLACK)
,43:(BLUE  ,BLACK)
,44:(BLUE  ,BLACK)
,45:(BLACK ,BLACK)
,46:(BLUE  ,BLACK)
,47:(BLUE  ,BLACK)
,48:(BLUE  ,BLACK)

,100:(CYAN, BLACK)

,243:(WHITE,  BLACK)
,244:(CYAN,   BLACK)
}
